use super::super::{CANVAS_NOT_TYPING, Command, Group, actions, always, several_pages};
use peek_canvas::Scope;

/// Cycling through the page's queries needs a query to cycle to. Unlike the selection commands
/// this counts every query on the page, because it selects one itself.
fn has_queries(scope: &Scope) -> bool {
    scope.queries > 0
}

pub(super) static ENTRIES: &[Command] = &[
    Command {
        id: "Page::New",
        title: "New page",
        label: None,
        group: Group::Page,
        keywords: "add tab",
        default_keys: &["meta-t"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::New),
        available: always,
    },
    Command {
        id: "Page::Close",
        title: "Close the current page",
        label: None,
        group: Group::Page,
        keywords: "delete remove page",
        default_keys: &["meta-w"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::Close),
        available: several_pages,
    },
    Command {
        id: "Page::Previous",
        title: "Previous page",
        label: None,
        group: Group::Page,
        keywords: "tab left",
        default_keys: &["meta-shift-["],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::Previous),
        available: several_pages,
    },
    Command {
        id: "Page::Next",
        title: "Next page",
        label: None,
        group: Group::Page,
        keywords: "tab right",
        default_keys: &["meta-shift-]"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::Next),
        available: several_pages,
    },
    Command {
        id: "Page::Search",
        title: "Search nodes on page",
        label: None,
        group: Group::Page,
        keywords: "find fuzzy search node jump go to",
        default_keys: &["meta-f"],
        // Bound page-wide, as the reference binds it. A result node that holds focus handles the
        // action first — its own listener sits deeper on the dispatch path, and an action stops
        // propagating in the bubble phase by default — so the same key is "find in result"
        // there and "search the page" everywhere else.
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::Search),
        available: always,
    },
    Command {
        id: "Page::GoToNode",
        title: "Go to a node",
        label: None,
        group: Group::Page,
        keywords: "go to jump navigate node label hint keyboard",
        default_keys: &["g"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::GoToNode),
        available: always,
    },
    Command {
        id: "Page::SelectNodeLeft",
        title: "Select node to the left",
        label: None,
        group: Group::Page,
        keywords: "select node move left arrow navigate keyboard",
        default_keys: &["meta-arrowleft"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectNodeLeft),
        available: always,
    },
    Command {
        id: "Page::SelectNodeRight",
        title: "Select node to the right",
        label: None,
        group: Group::Page,
        keywords: "select node move right arrow navigate keyboard",
        default_keys: &["meta-arrowright"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectNodeRight),
        available: always,
    },
    Command {
        id: "Page::SelectNodeUp",
        title: "Select node above",
        label: None,
        group: Group::Page,
        keywords: "select node move up arrow navigate keyboard",
        default_keys: &["meta-arrowup"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectNodeUp),
        available: always,
    },
    Command {
        id: "Page::SelectNodeDown",
        title: "Select node below",
        label: None,
        group: Group::Page,
        keywords: "select node move down arrow navigate keyboard",
        default_keys: &["meta-arrowdown"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectNodeDown),
        available: always,
    },
    Command {
        id: "Page::OpenPicker",
        title: "Open the pages picker",
        label: None,
        group: Group::Page,
        keywords: "pages list menu switch picker",
        default_keys: &["o"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::OpenPicker),
        available: several_pages,
    },
    Command {
        id: "Page::SelectPreviousQuery",
        title: "Select previous query",
        label: None,
        group: Group::Page,
        keywords: "query previous cycle select navigate",
        default_keys: &["meta-["],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectPreviousQuery),
        available: has_queries,
    },
    Command {
        id: "Page::SelectNextQuery",
        title: "Select next query",
        label: None,
        group: Group::Page,
        keywords: "query next cycle select navigate",
        default_keys: &["meta-]"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::page::SelectNextQuery),
        available: has_queries,
    },
];
