use super::super::{CANVAS, CANVAS_NOT_TYPING, Command, Group, actions, always};

pub(super) static ENTRIES: &[Command] = &[
    Command {
        id: "Tool::Select",
        title: "Clear selection",
        label: None,
        group: Group::Tool,
        keywords: "deselect escape",
        default_keys: &["escape"],
        // The bare context, not the `!Input` predicate: escape has to disarm a tool and cancel
        // jump mode while an editor holds focus too.
        context: CANVAS,
        build: || Box::new(actions::tool::Select),
        available: always,
    },
    Command {
        id: "Tool::Query",
        title: "New query node",
        label: None,
        group: Group::Tool,
        keywords: "place add sql select",
        default_keys: &["q"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::tool::Query),
        available: always,
    },
    Command {
        id: "Tool::Agent",
        title: "New agent node",
        label: None,
        group: Group::Tool,
        keywords: "place add ai chat llm assistant",
        default_keys: &["a"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::tool::Agent),
        available: always,
    },
    Command {
        id: "Tool::Text",
        title: "New text node",
        label: None,
        group: Group::Tool,
        keywords: "place add note label",
        default_keys: &["t"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::tool::Text),
        available: always,
    },
    Command {
        id: "Tool::Variable",
        title: "New variable node",
        label: None,
        group: Group::Tool,
        keywords: "place add vars parameter",
        default_keys: &["v"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::tool::Variable),
        available: always,
    },
    Command {
        id: "Tool::Draw",
        title: "Draw",
        label: None,
        group: Group::Tool,
        keywords: "pen freehand sketch stroke ink annotate",
        default_keys: &["d"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::tool::Draw),
        available: always,
    },
];
