use super::super::{CANVAS_NOT_TYPING, Command, Group, actions, always, has_selected_nodes};

pub(super) static ENTRIES: &[Command] = &[
    Command {
        id: "Zoom::In",
        title: "Zoom in",
        label: None,
        group: Group::Zoom,
        keywords: "bigger closer",
        default_keys: &["meta-="],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::In),
        available: always,
    },
    Command {
        id: "Zoom::Out",
        title: "Zoom out",
        label: None,
        group: Group::Zoom,
        keywords: "smaller further",
        default_keys: &["meta--"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::Out),
        available: always,
    },
    Command {
        id: "Zoom::Reset",
        title: "Reset zoom to 100%",
        label: None,
        group: Group::Zoom,
        keywords: "actual size",
        default_keys: &["meta-0"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::Reset),
        available: always,
    },
    Command {
        id: "Zoom::FitView",
        title: "Fit all nodes in view",
        label: None,
        group: Group::Zoom,
        keywords: "fit view frame everything",
        default_keys: &["meta-shift-0"],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::FitView),
        available: always,
    },
    Command {
        id: "Zoom::FitSelection",
        title: "Fit selected nodes in view",
        label: None,
        group: Group::Zoom,
        keywords: "frame selection",
        default_keys: &[],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::FitSelection),
        available: has_selected_nodes,
    },
    Command {
        id: "Zoom::FitSelectionAndLock",
        title: "Fit nodes to view and lock camera",
        label: None,
        group: Group::Zoom,
        keywords: "fit nodes view zoom tile lock camera freeze present",
        default_keys: &[],
        context: CANVAS_NOT_TYPING,
        build: || Box::new(actions::zoom::FitSelectionAndLock),
        available: has_selected_nodes,
    },
];
